### ISSUE TITLE
Transactions: Visa tracker

### ISSUE THREAD

**Issue by amyr11** [amyr11/Skywander-App#17]
# Frontend

- [ ] Display summary of visa
- [ ] Display requirements and status

# Backend

- [ ] Fetch visa transaction in database
- [ ] Upload requirements in visa transaction
